apiVersion: v1
kind: Service
metadata:
  name: springbootapp-otelcollector-deployment-service
  namespace: ajprakash
  labels:
    name: springbootapp-otelcollector-deployment-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - protocol: TCP
      port: 8080
      targetPort: 8282
  selector:
    app: springbootapp-otelcollector-pod
