apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-otelcollector-deployment
  namespace: ajprakash
  labels:
    app: springbootapp-otelcollector-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp-otelcollector-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: springbootapp-otelcollector-pod
    spec:
      containers:
        - name: mongo-db
          image: mongo

        - name: mongo-service
          image: ajprakash/opentelemetry-mongo-service:1.0
          args: [ "--spring.data.mongodb.database=user_db","--spring.data.mongodb.port=27017","--spring.data.mongodb.host=localhost" ]

        - name: user-service
          image: ajprakash/opentelemetry-user-service:1.0
          ports:
            - containerPort: 8282
          args: [ "--db.host=localhost","--db.port=8080","--otel-collector_host=10.196.173.72","--otel-collector_port=4317","--otel-collector_useSsl=false"]
      imagePullSecrets:
        - name: ajprakash-docker-secrets
