FROM maven:3.6.1-jdk-8-alpine AS MAVEN_BUILD

MAINTAINER Ajay Prakash

COPY pom.xml /build/

COPY src /build/src/

WORKDIR /build/

RUN mvn package

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/userApp-1.0-SNAPSHOT.jar /app/

ENTRYPOINT ["java", "-jar", "userApp-1.0-SNAPSHOT.jar"]

